[project]
name = "pixel-groove"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "yt-dlp>=2026.2.4",
]

[tool.uv.workspace]
members = ["backend"]
